// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

// Layer-specific mappings for outer column customization
#define MIRYOKU_LAYERMAPPING_BUTTON MIRYOKU_LAYOUTMAPPING_BUTTON
#define MIRYOKU_LAYERMAPPING_NAV MIRYOKU_LAYOUTMAPPING_NAV
#define MIRYOKU_LAYERMAPPING_MOUSE MIRYOKU_LAYOUTMAPPING_MOUSE
#define MIRYOKU_LAYERMAPPING_MEDIA MIRYOKU_LAYOUTMAPPING_MEDIA
#define MIRYOKU_LAYERMAPPING_NUM MIRYOKU_LAYOUTMAPPING_NUM
#define MIRYOKU_LAYERMAPPING_SYM MIRYOKU_LAYOUTMAPPING_SYM
#define MIRYOKU_LAYERMAPPING_FUN MIRYOKU_LAYOUTMAPPING_FUN
