name: 'Build Corne V4 Pro Micro: Qwerty'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      clipboard: '["mac"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16"]'
      nav: '["invertedt"]'